version: "3.2"
services:
  php:
    image : base_php:latest
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php_${DOMAIN}
  apache:
    image : base_apache:latest
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache_${DOMAIN}
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - "${MYSQL_PORT}"
    volumes:
            - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql_${DOMAIN}
networks:
  frontend:
  backend:
volumes:
    data:
